# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'labels', 'predict']

# %% ../app.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% ../app.ipynb 3
learn = load_learner('export.pkl')

# %% ../app.ipynb 4
labels = learn.dls.vocab
def predict(img):
    img = PILImage.create(img)
    pred,pred_idx,probs = learn.predict(img)
    return {labels[i]: float(probs[i]) for i in range(len(labels))}

# %% ../app.ipynb 5
gr.Interface(fn=predict, inputs=gr.Image(height=512, width=512), \
    outputs=gr.Label(num_top_classes=3)).launch(share=True)
